#!/usr/bin/env python3
"""skillsync — keep htmldrill's command surface coherent from ONE source of truth.

The single source of truth is ``src/htmldrill/commands.yaml`` (the same file the
planner reads). From it:
  * check         validate the manifest against cli.py's HANDLERS dict (the only
                  ground truth for which commands exist) — the CI drift gate.
  * render-help   emit the --help body to ``src/htmldrill/_help_generated.txt``.
  * render-skill  regenerate the command tables in ``SKILL.md`` between the
                  <!-- COMMANDS:BEGIN/END --> markers, preserving authored prose.
  * all           check + render-help + render-skill.

Adapted from pdfdrill's skillsync. Differences: htmldrill keeps ONE manifest in
the package (not a separate .claude/skills copy), SKILL.md lives at the repo root,
and the HANDLERS regex matches htmldrill's column-0 closing brace. pyyaml only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

BEGIN = "<!-- COMMANDS:BEGIN (generated by skillsync — do not edit by hand) -->"
END = "<!-- COMMANDS:END -->"

MANIFEST_REL = "src/htmldrill/commands.yaml"
CLI_REL = "src/htmldrill/cli.py"
HELP_REL = "src/htmldrill/_help_generated.txt"
SKILL_REL = "SKILL.md"


def load_manifest(repo: Path) -> dict:
    return yaml.safe_load((repo / MANIFEST_REL).read_text(encoding="utf-8"))


def handler_names(repo: Path) -> list[str]:
    """The ground truth: the module-level HANDLERS dict in commands.py/cli.py.

    htmldrill defines HANDLERS in commands.py and imports it into cli.py, so read
    commands.py. The closing brace sits at column 0 (normal Python style)."""
    src = (repo / "src/htmldrill/commands.py").read_text(encoding="utf-8")
    m = re.search(r"HANDLERS\s*=\s*\{(.*?)\n\}", src, re.S)
    if not m:
        raise SystemExit("could not locate the HANDLERS dict in commands.py")
    return [g.group(1) for g in re.finditer(r'"(\w+)":', m.group(1))]


def usage_string(cmd: dict) -> str:
    parts = [f"<{p['name']}>" for p in cmd.get("positionals", [])]
    for f in cmd.get("flags", []):
        token = f["flag"]
        if f.get("type") == "flag":
            parts.append(f"[{token}]")
        else:
            ph = (f.get("choices") and "|".join(f["choices"])) or f.get("name", "X").upper()
            parts.append(f"[{token} {ph}]")
    return " ".join(parts)


def cmd_check(repo: Path) -> int:
    man = load_manifest(repo)
    man_names = [c["name"] for c in man["commands"]]
    hset, mset = set(handler_names(repo)), set(man_names)
    issues = 0
    missing = sorted(hset - mset)
    extra = sorted(mset - hset)
    dupes = sorted({n for n in man_names if man_names.count(n) > 1})

    print(f"handlers (truth): {len(hset)}   manifest: {len(mset)}")
    if missing:
        issues += 1; print(f"✗ in HANDLERS but MISSING from manifest: {missing}")
    if extra:
        issues += 1; print(f"✗ in manifest but NOT a handler (stale): {extra}")
    if dupes:
        issues += 1; print(f"✗ duplicate manifest entries: {dupes}")
    if not issues:
        print("✓ manifest ↔ HANDLERS: in sync")
    return 1 if issues else 0


def render_help_text(man: dict) -> str:
    lines = ["htmldrill — token-economical drill-down toolkit for HTML documents", ""]
    by_section: dict[str, list[dict]] = {}
    for c in man["commands"]:
        by_section.setdefault(c["section"], []).append(c)
    for section, cmds in by_section.items():
        lines.append(f"{section}:")
        for c in cmds:
            left = f"  htmldrill {c['name']} {usage_string(c)}".rstrip()
            pad = " " if len(left) >= 46 else ""
            lines.append(f"{left:<46}{pad}{c['summary']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def cmd_render_help(repo: Path) -> int:
    man = load_manifest(repo)
    out = repo / HELP_REL
    out.write_text(render_help_text(man), encoding="utf-8")
    print(f"wrote {out}  ({len(man['commands'])} commands)")
    return 0


def render_tables(man: dict) -> str:
    by_section: dict[str, list[dict]] = {}
    for c in man["commands"]:
        by_section.setdefault(c["section"], []).append(c)
    out = [BEGIN, "", "## Command reference", "",
           "_Generated from `commands.yaml` by skillsync. Edit the manifest, not this section._", ""]
    for section, cmds in by_section.items():
        out += [f"### {section}", "", "| Command | Returns |", "|---|---|"]
        for c in cmds:
            sig = f"`htmldrill {c['name']} {usage_string(c)}`".rstrip("` ") + "`"
            summary = c["summary"].replace("|", "\\|")
            tag = " _(network)_" if c.get("network") else ""
            out.append(f"| {sig} | {summary}{tag} |")
        out.append("")
    out.append(END)
    return "\n".join(out)


def cmd_render_skill(repo: Path) -> int:
    man = load_manifest(repo)
    skill = repo / SKILL_REL
    text = skill.read_text(encoding="utf-8")
    region = render_tables(man)
    if BEGIN in text and END in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), region, text, flags=re.S)
    else:
        text = text.rstrip() + "\n\n" + region + "\n"
    skill.write_text(text, encoding="utf-8")
    print(f"synced {skill}  ({len(man['commands'])} commands between markers)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="sync htmldrill SKILL/help from commands.yaml")
    ap.add_argument("action", choices=["check", "render-help", "render-skill", "all"])
    ap.add_argument("repo", nargs="?", default=".")
    a = ap.parse_args()
    repo = Path(a.repo)
    if a.action == "check":
        return cmd_check(repo)
    if a.action == "render-help":
        return cmd_render_help(repo)
    if a.action == "render-skill":
        return cmd_render_skill(repo)
    if a.action == "all":
        rc = cmd_check(repo)
        cmd_render_help(repo)
        cmd_render_skill(repo)
        return rc
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
